insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (1, 'Quality-focused reciprocal open architecture', '£27.05', 749);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (2, 'Re-contextualized contextually-based archive', '£38.51', 575);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (3, 'Upgradable multimedia utilisation', '£16.80', 373);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (4, 'User-friendly local success', '£43.09', 415);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (5, 'Versatile didactic emulation', '£49.67', 300);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (6, 'Diverse grid-enabled capacity', '£34.38', 284);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (7, 'Customer-focused exuding info-mediaries', '£24.69', 330);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (8, 'Polarised tertiary Graphic Interface', '£16.87', 165);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (9, 'Reactive eco-centric neural-net', '£28.47', 523);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (10, 'Inverse static hierarchy', '£5.22', 330);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (11, 'User-friendly context-sensitive challenge', '£4.67', 33);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (12, 'Switchable uniform archive', '£48.64', 506);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (13, 'Quality-focused intermediate definition', '£17.43', 498);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (14, 'Total multi-tasking flexibility', '£42.33', 731);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (15, 'Re-contextualized executive workforce', '£26.65', 426);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (16, 'Team-oriented contextually-based standardization', '£34.63', 765);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (17, 'Diverse maximized leverage', '£33.60', 932);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (18, 'Reactive context-sensitive attitude', '£41.04', 39);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (19, 'Organized optimizing workforce', '£3.26', 360);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (20, 'Exclusive homogeneous success', '£23.98', 736);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (21, 'Synchronised 5th generation customer loyalty', '£48.72', 618);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (22, 'Cross-group clear-thinking concept', '£33.71', 927);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (23, 'Sharable mobile software', '£46.95', 818);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (24, 'Operative web-enabled hub', '£24.66', 361);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (25, 'Organic reciprocal hub', '£11.49', 207);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (26, 'Sharable bifurcated frame', '£41.45', 228);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (27, null, '£4.58', 720);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (28, 'Open-architected transitional hub', '£43.71', 125);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (29, 'Monitored demand-driven infrastructure', '£1.78', 527);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (30, 'Polarised bifurcated secured line', '£33.98', 854);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (31, 'Object-based discrete approach', '£22.09', 959);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (32, 'Synergized zero defect installation', '£12.83', 126);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (33, 'Synchronised analyzing structure', '£48.83', 555);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (34, 'Switchable high-level array', '£13.93', 183);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (35, 'Digitized non-volatile help-desk', '£34.29', 906);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (36, 'Cross-group object-oriented budgetary management', '£24.22', 924);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (37, 'Advanced analyzing throughput', '£14.59', 475);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (38, 'Reduced scalable throughput', '£38.24', 368);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (39, 'Front-line web-enabled function', '£38.04', 870);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (40, 'Cross-group 4th generation implementation', '£26.87', 137);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (41, 'Synergized coherent website', '£46.25', 718);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (42, 'Multi-layered client-server groupware', '£7.98', 38);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (43, 'Realigned web-enabled local area network', '£21.13', 237);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (44, 'Public-key regional framework', '£39.59', 453);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (45, 'Streamlined non-volatile Graphical User Interface', '£28.80', 539);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (46, 'Expanded leading edge complexity', '£46.74', 728);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (47, 'Balanced content-based leverage', '£6.06', 662);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (48, 'Inverse reciprocal service-desk', '£13.39', 329);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (49, 'Organic methodical frame', '£43.88', 361);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (50, 'Profound high-level installation', '£20.52', 465);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (51, 'Face to face non-volatile middleware', '£11.21', 910);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (52, 'Polarised client-server core', '£35.90', 429);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (53, null, '£43.99', 602);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (54, 'Reduced systemic model', '£7.95', 109);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (55, 'Extended bandwidth-monitored concept', '£9.04', 676);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (56, 'Optimized transitional neural-net', '£3.66', 685);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (57, 'Assimilated mission-critical system engine', '£48.71', 20);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (58, 'Centralized 6th generation circuit', '£27.87', 120);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (59, 'Face to face next generation productivity', '£41.18', 854);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (60, 'Mandatory optimal approach', '£17.74', 857);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (61, 'Enterprise-wide fresh-thinking customer loyalty', '£16.55', 489);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (62, 'Fundamental methodical firmware', '£28.85', 405);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (63, 'Realigned homogeneous collaboration', '£14.16', 455);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (64, 'Optimized holistic system engine', '£49.42', 406);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (65, 'Mandatory optimal open system', '£44.86', 405);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (66, 'Stand-alone motivating open system', '£6.54', 870);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (67, 'Open-source uniform initiative', '£47.46', 193);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (68, 'Automated tertiary product', '£45.70', 470);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (69, 'Intuitive directional concept', '£32.32', 493);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (70, 'Multi-lateral cohesive website', '£27.77', 636);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (71, 'Switchable needs-based algorithm', '£20.43', 18);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (72, null, '£44.53', 164);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (73, 'Cloned motivating software', '£4.72', 414);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (74, 'Optional bottom-line open architecture', '£39.80', 920);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (75, 'Assimilated 4th generation protocol', '£41.37', 147);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (76, 'Proactive bandwidth-monitored migration', '£19.50', 380);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (77, 'Managed modular workforce', '£40.77', 689);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (78, 'Down-sized multi-tasking capacity', '£43.64', 640);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (79, 'Fully-configurable static contingency', '£10.41', 817);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (80, 'Quality-focused multi-tasking help-desk', '£2.64', 126);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (81, 'Innovative intangible paradigm', '£2.35', 457);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (82, 'Future-proofed clear-thinking collaboration', '£15.99', 382);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (83, 'Multi-channelled didactic product', '£15.44', 926);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (84, 'Automated solution-oriented firmware', '£10.59', 265);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (85, 'Enhanced intangible success', '£21.58', 75);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (86, 'Down-sized fresh-thinking projection', '£7.93', 138);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (87, 'Re-contextualized multi-state parallelism', '£6.02', 756);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (88, 'Business-focused asymmetric paradigm', '£39.97', 804);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (89, 'User-centric regional process improvement', '£25.56', 391);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (90, 'Multi-tiered mobile pricing structure', '£13.99', 893);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (91, 'Visionary uniform protocol', '£1.78', 840);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (92, 'Horizontal system-worthy flexibility', '£15.64', 832);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (93, 'Fundamental user-facing database', '£37.04', 247);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (94, 'Stand-alone hybrid paradigm', '£19.91', 947);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (95, 'Mandatory stable synergy', '£30.51', 87);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (96, 'Proactive bi-directional support', '£14.70', 281);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (97, 'Open-source context-sensitive groupware', '£40.06', 524);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (98, 'Future-proofed responsive intranet', '£20.29', 62);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (99, 'Enterprise-wide methodical initiative', '£31.95', 532);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (100, 'Enterprise-wide homogeneous system engine', '£13.63', 470);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (101, 'Stand-alone 24 hour capability', '£30.99', 650);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (102, 'Polarised contextually-based infrastructure', '£42.80', 918);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (103, 'Future-proofed dynamic contingency', '£32.47', 576);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (104, 'Diverse 6th generation application', '£10.85', 971);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (105, 'Multi-layered tangible process improvement', '£41.36', 326);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (106, 'Self-enabling value-added concept', '£24.79', 67);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (107, 'Expanded multimedia challenge', '£35.98', 324);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (108, 'Devolved scalable throughput', '£19.99', 599);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (109, 'Focused 3rd generation utilisation', '£21.42', 899);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (110, 'Polarised clear-thinking forecast', '£4.21', 243);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (111, 'Right-sized zero administration groupware', '£6.35', 835);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (112, null, '£28.01', 475);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (113, 'Optimized global structure', '£28.48', 217);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (114, 'Visionary static encoding', '£26.52', 987);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (115, 'Versatile fresh-thinking frame', '£24.41', 291);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (116, 'Virtual responsive core', '£20.96', 883);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (117, 'Ameliorated hybrid internet solution', '£22.75', 207);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (118, 'Triple-buffered full-range encryption', '£19.26', 526);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (119, 'Synergized empowering middleware', '£7.90', 826);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (120, 'Extended even-keeled access', '£45.47', 251);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (121, 'Extended human-resource forecast', '£36.44', 858);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (122, 'Public-key clear-thinking product', '£49.11', 235);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (123, 'De-engineered exuding process improvement', '£48.18', 64);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (124, 'Streamlined motivating website', '£41.87', 980);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (125, 'Vision-oriented exuding system engine', '£3.26', 567);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (126, 'Ameliorated executive open system', '£33.17', 471);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (127, 'Secured cohesive extranet', '£14.92', 197);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (128, 'Operative background application', '£18.57', 673);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (129, 'Object-based didactic array', '£32.68', 790);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (130, 'Phased explicit alliance', '£15.57', 801);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (131, 'Object-based 3rd generation intranet', '£37.84', 688);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (132, 'Customer-focused zero defect info-mediaries', '£20.29', 205);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (133, 'Distributed multi-state parallelism', '£31.00', 649);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (134, null, '£17.98', 402);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (135, 'Mandatory global knowledge base', '£37.04', 816);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (136, 'Triple-buffered secondary throughput', '£8.53', 344);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (137, 'Persistent high-level core', '£7.76', 270);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (138, 'Object-based eco-centric model', '£33.60', 448);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (139, 'Front-line motivating attitude', '£7.01', 206);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (140, 'Sharable optimizing intranet', '£36.87', 337);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (141, 'Distributed non-volatile open architecture', '£21.21', 69);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (142, 'Open-source client-driven customer loyalty', '£13.34', 247);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (143, 'Profit-focused next generation protocol', '£47.01', 408);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (144, 'Switchable transitional workforce', '£38.67', 244);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (145, 'Business-focused dynamic productivity', '£1.34', 441);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (146, 'De-engineered incremental service-desk', '£9.92', 153);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (147, 'Distributed fresh-thinking capacity', '£6.42', 877);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (148, 'Secured system-worthy conglomeration', '£24.07', 712);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (149, 'De-engineered responsive ability', '£14.05', 124);
insert into inventory (ProductID, ProductDesc, ProductPrice, ProductStockAmount) values (150, 'Managed interactive challenge', '£44.25', 698);
